name: Publish package

on:
  workflow_dispatch:
    inputs:
      aeq_39_and_below_version:
        description: 'AequilibraE version for Python 3.9 and below'
        required: true
        default: '0.9.1.dev0'
        type: string
      aeq_above_39_version:
        description: 'AequilibraE version for above Python 3.9'
        required: true
        default: '0.9.1'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      - name: Replace requirements
        run: >-
          sed -e "s/\(aequilibrae==\)\(.*\?\)\(;python_version<=\"3.9\"\)/\${{ inputs.aeq_39_and_below_version }}\3/" \
              -e "s/\(aequilibrae==\)\(.*\?\)\(;python_version>\"3.9\"\)/\1${{ inputs.aeq_above_39_version }}\3/" \
              ./qaequilibrae/requirements.txt
      # - name: Deploy plugin
      #   run: >-
      #     qgis-plugin-ci
      #     release ${GITHUB_REF/refs\/tags\//}
      #     --github-token ${{ secrets.GITHUB_TOKEN }}
      #     --osgeo-username ${{ secrets.QGIS_PLUGIN_REPO_USER }}
      #     --osgeo-password ${{ secrets.QGIS_PLUGIN_REPO_PASSWORD }}
      - name: Create archive
        run: >-
          qgis-plugin-ci
          package ${{ github.ref_name }}
